LIDL 1e versie APV
RoleplayNL/Wetten pull request #4
Opened 2023-06-08 15:53 UTC by emshov74

APV is leuk

Lost issue #  op.

#### Wijzigingen voorgesteld in deze pull-request

- 

- [ ] ik heb het getest en geverifieerd dat alles werkt.

2023-06-09 19:57 UTC, Edward-Bakker requested changes
Feedback op de aanpassingen in de RVV 1990

2023-06-09 19:57 UTC, Edward-Bakker commented on docs/wegenverkeerswet/rvv-1990.md
> -    1. voor motorvoertuigen 50 km per uur;
Dit moet in overleg met management voordat er afgeweken gaat worden van irl. De huidige snelheid in de stad is onbekend.

2023-06-09 19:57 UTC, Edward-Bakker commented on docs/wegenverkeerswet/rvv-1990.md
> -    1. voor motorvoertuigen op autosnelwegen 130 km per uur, op autowegen 100 km per uur en op andere wegen 80 km per uur;
Hetzelfde hier, is er al duidelijk of er geen autowegen zijn of in een later stadium toegevoegd gaan worden.

2023-06-09 19:57 UTC, Edward-Bakker commented on docs/wegenverkeerswet/rvv-1990.md
> +        2. op de rijbaan 130 km per uur;
Loophole, motorvoertuig op andere wegen 80 km/u, maar bromfietsen 130 km/u. Hetzelfde laten als irl of loophole fixen.

2023-06-11 09:57 UTC, JarieTimmer commented
Ga je deze nog afmaken @emshov74 ?
graag even iets vaart achter zetten.

2023-06-11 19:00 UTC, emshov74 commented
> Ga je deze nog afmaken @emshov74 ? graag even iets vaart achter zetten.

wil je zo graag dood bij de belastingdienst? Anders help ik je wel een handje*

_*Dit is een grap, geen bedreiging van een overheidsmedewerker_

2023-06-17 14:48 UTC, Edward-Bakker approved these changes
lgtm!

2023-06-17 14:50 UTC, merged