APV is af
RoleplayNL/Wetten pull request #9
Opened 2023-06-21 04:26 UTC by emshov74

#### Wijzigingen voorgesteld in deze pull-request

- APV in zijn volledigheid

- [🗸] ik heb het getest en geverifieerd dat alles werkt.

*Graag voorzien van feedback omdat ik niet enkel een APV pro ben maar ook een versiebeheer pro die 100% weet wat die doet*

2023-06-22 13:25 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +    3. namens de burgemeester handelende ambtenaren van de gemeente Future.
De kwalificatie van dit artikel spreekt over `Toezichthouders`, maar hier gaat het over het verlenen van vergunning. Zou het tweede lid aan de kwalificatie toegevoegd kunnen worden, of eventueel een apart artikel hiervoor.

2023-06-22 13:39 UTC, Edward-Bakker requested changes

2023-06-22 13:39 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +   5. APV-controleur bij de gemeente Future;
In het artikel 1:2, eerste lid wordt 4 keer de buitengewoon opsporingsambtenaar aangehaald. Ik zie ook artikel 142 Wetboek van Strafvordering naar gerefeerd worden, het artikel dat gaat over de boa, maar deze ontbreekt in de wettenbundel vanwege het feit dat FutureRP geen boa heeft.

2023-06-22 13:39 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +   3. namens de burgemeester handelende ambtenaren van de gemeente Future.
De kwalificatie van dit artikel spreekt over `Toezichthouders`, zou het tweede lid opgenomen kunnen worden in de kwalificatie of eventueel worden opgenomen in een vrijstaand artikel.

2023-06-22 13:39 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +5. Het is verboden om zich in strijd met een op grond van dit artikel opgelegde gebiedsontzegging in een desbetreffend door het college aangewezen gebied of de daarin voor publiek toegankelijke gebou
Is er een reden waarom een gebiedsontzegging zo absurd hoog wordt gestraft? Het gaat hier om een overtreding in een APV, krachtens de Gemeentewet opgesteld. In artikel 154 van de wet staat het volgende:

> hechtenis van ten hoogste drie maanden of geldboete van de tweede categorie, al dan niet met openbaarmaking van de rechterlijke uitspraak.

2023-06-22 13:39 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +2. Het in het eerste lid gestelde verbod geldt niet voor zover in het daarin geregelde onderwerp wordt voorzien door artikel 424, of 426bis, of Titel XX van het Wetboek van Strafrecht.
Dit artikel is overbodig, artikel 141 WvSr dat spreekt over openlijke geweldpleging is al opgenomen in de wettenbundel.

2023-06-22 13:39 UTC, Edward-Bakker commented on docs/algemene-plaatselijke-verordening.md
> +2. Van hinder of overlast is in elk geval sprake wanneer de fiets voor een gevel van een pand is neergezet terwijl dit in strijd is met de uitdrukkelijk verklaarde wil van de gebruiker van dat pand,
Zover ik zie valt dit al onder artikel 27 van de RVV 1990 en/of artikel 424 WvSr dat spreekt over straatschenderij.

2023-06-22 18:00 UTC, emshov74 commented on docs/algemene-plaatselijke-verordening.md
> +   5. APV-controleur bij de gemeente Future;
dan haal je lid 3 weg ofzo

2023-06-22 18:02 UTC, emshov74 commented on docs/algemene-plaatselijke-verordening.md
> +   3. namens de burgemeester handelende ambtenaren van de gemeente Future.
misschien dan 2e lid opnemen in een nieuw artikel 1:2a

2023-06-22 18:03 UTC, emshov74 commented on docs/algemene-plaatselijke-verordening.md
> +2. Het in het eerste lid gestelde verbod geldt niet voor zover in het daarin geregelde onderwerp wordt voorzien door artikel 424, of 426bis, of Titel XX van het Wetboek van Strafrecht.
niet wanneer het gaat om een vechtpartij met wederzijds goedvinden, dat is waar het artikel op is gericht

2023-06-22 18:03 UTC, emshov74 commented on docs/algemene-plaatselijke-verordening.md
> +2. Van hinder of overlast is in elk geval sprake wanneer de fiets voor een gevel van een pand is neergezet terwijl dit in strijd is met de uitdrukkelijk verklaarde wil van de gebruiker van dat pand,
prima, dan schrappen we die

2023-06-24 18:32 UTC, Edward-Bakker approved these changes
lgtm!

2023-06-24 18:33 UTC, merged